---
name: Manually Compile

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

jobs:
  build:

    name: Maven build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@master
      with:
        distribution: 'zulu'
        java-version: 8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Deploy Javadoc
      uses: MathieuSoysal/publish-javadoc@v2.3.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        javadoc-branche: javadoc
        java-version: 8
        target-folder: javadoc
        java-distribution: zulu
